# Generated by Django 3.1.5 on 2021-01-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='good_match',
            field=models.BooleanField(default=True, verbose_name='Good Match'),
        ),
    ]
