# Generated by Django 3.1.5 on 2021-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_jobmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Show'),
        ),
    ]
