# Generated by Django 3.1.5 on 2021-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlist',
            name='read_at',
            field=models.DateField(blank=True, null=True, verbose_name='Read at'),
        ),
    ]
