# Generated by Django 3.1.5 on 2021-02-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directmessages.directmessage', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='replied',
            field=models.BooleanField(default=False, verbose_name='Replied'),
        ),
    ]
