# Generated by Django 3.1.5 on 2021-02-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0002_auto_20210202_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read date'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
