# Generated by Django 3.1.5 on 2021-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='importance_level',
            field=models.CharField(blank=True, default='Somewhat Important', max_length=50, null=True, verbose_name='Importance Level'),
        ),
    ]
