# Generated by Django 3.1.5 on 2021-01-27 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0003_useranswer_importance_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='points',
            field=models.IntegerField(default='20', verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='Answer'),
        ),
        migrations.CreateModel(
            name='MatchAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance_level', models.CharField(blank=True, default='Somewhat Important', max_length=50, null=True, verbose_name='Importance Level')),
                ('points', models.IntegerField(default='20', verbose_name='Points')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'MatchAnswer',
                'verbose_name_plural': 'MatchAnswers',
            },
        ),
    ]
